### ISSUE TITLE
EINTR improperly handled for select() in blocking_kinetic_connection.cc

### ISSUE THREAD

**Issue by golpa** [Kinetic/kinetic-cpp-client#46]
The `EINTR` condition in `select` should not be treated as an error since it can happen during normal operations in Linux. Instead the caller should redo the `select` call.

I've submitted a pull request for these changes https://github.com/Kinetic/kinetic-cpp-client/pull/45

**Comment by plensing** [comment]
You are correct, I have merged the pull request. I have also implemented the improvements you suggested in the comments of your pull request and will merge them in soon. 
Thank you for finding and fixing this issue.
